############################################################
# resources
############################################################
# https://github.com/tmux/tmux/wiki/Getting-Started
# https://man.openbsd.org/OpenBSD-current/man1/tmux.1

unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.tmux.conf \; display-message "Reloaded."
bind K run-shell -b $HOME/.tmux/plugins/tmux-fuzm/fuzm.tmux

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g history-limit 50000

############################################################
# Mouse Support
############################################################

set -g mouse on

# Toggle mouse support (M-m is alt-m)
bind M-m set-option -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

set -g set-clipboard on
bind -Tcopy-mode MouseDragEnd1Pane send -X copy-selection-and-cancel

# Display pane numbers and select
bind q display-panes

# Lock session
bind-key L lock-session


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

############################################################
# Status Bar
############################################################

set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @theme_transparent_status_bar 'true'

set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'conorwarrilow/tmux-fzm'

# tmux-continuum must be below status bar theme plugins
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g status-right 'Continuum status: #{continuum_status}'

set -gq allow-passthrough on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

set -g @sessionx-bind 'o'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-window-mode 'off'

set -g @fuzm-launch 'f'

# Keep at the bottom
run '~/.tmux/plugins/tpm/tpm'
# Override tokyonight theme active border color
set -g pane-active-border-style fg=#2ac3de,bg=default

############################################################
# Transparency block support
############################################################

set-environment -g TRANSPARENT_FULL_BLOCKS "$TRANSPARENT_FULL_BLOCKS"

if-shell '[ "$TRANSPARENT_FULL_BLOCKS" = "true" ]' \
  'set -g mode-style "fg=#c6c6c6,bg=#401F25"' \
  'set -g mode-style "fg=black,bg=#bb9bf7"'
